-- Rechte einheitlich: je Bereich Sehen, Erstellen, Bearbeiten, Status, Löschen.
-- Was jemand bisher durfte, gilt unter den neuen Namen weiter; ganz neue Rechte
-- (z. B. Bestand sehen) ergänzt der Start aus den Standardrechten im Code.
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'lager.bestand.buchen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'lager.stock.book';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'lager.bestand.inventur', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'lager.stock.inventory';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'lager.bewegungen.sehen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'lager.movements.view';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'lager.bewegungen.bearbeiten', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'lager.movements.correct';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'lager.artikel.erstellen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'lager.products.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'lager.artikel.bearbeiten', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'lager.products.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'lager.artikel.loeschen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'lager.products.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'lager.berichte.sehen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'lager.reports.view';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'lager.warnungen.sehen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'lager.alerts.view';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'stunden.sehen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'stunden.erfassen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'stunden.erstellen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'stunden.erfassen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'stunden.bearbeiten', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'stunden.erfassen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'stunden.loeschen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'stunden.erfassen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'tagesberichte.erstellen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'tagesberichte.erfassen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'tagesberichte.bearbeiten', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'tagesberichte.erfassen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'tagesberichte.loeschen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'tagesberichte.erfassen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'angebote.bearbeiten', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'angebote.erstellen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'angebote.loeschen.entwurf', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'angebote.erstellen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'kunden.sehen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'kunden.pflegen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'kunden.erstellen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'kunden.pflegen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'kunden.bearbeiten', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'kunden.pflegen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'kunden.loeschen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'kunden.pflegen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'auftraege.bearbeiten', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'auftraege.erstellen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'auftraege.status.zuruecksetzen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'auftraege.erstellen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'auftraege.loeschen.neu', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'auftraege.erstellen';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'stammdaten.sehen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'verwaltung.masterdata.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'stammdaten.erstellen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'verwaltung.masterdata.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'stammdaten.bearbeiten', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'verwaltung.masterdata.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'stammdaten.loeschen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'verwaltung.masterdata.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'benutzer.sehen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'verwaltung.users.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'benutzer.erstellen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'verwaltung.users.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'benutzer.bearbeiten', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'verwaltung.users.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'benutzer.loeschen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'verwaltung.users.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'berechtigungen.sehen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'verwaltung.permissions.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'berechtigungen.bearbeiten', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'verwaltung.permissions.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'einstellungen.sehen', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'verwaltung.settings.manage';--> statement-breakpoint
INSERT OR REPLACE INTO `role_permissions` (`role`, `permission`, `allowed`, `updated_at`) SELECT `role`, 'einstellungen.bearbeiten', `allowed`, `updated_at` FROM `role_permissions` WHERE `permission` = 'verwaltung.settings.manage';--> statement-breakpoint
-- Wer alle sehen bzw. bearbeiten durfte, sieht bzw. bearbeitet auch die eigene Partie
UPDATE `role_permissions` SET `allowed` = 1 WHERE `permission` = 'stunden.sehen' AND `role` IN (SELECT `role` FROM `role_permissions` WHERE `permission` IN ('stunden.alle.sehen', 'stunden.alle.bearbeiten') AND `allowed` = 1);--> statement-breakpoint
UPDATE `role_permissions` SET `allowed` = 1 WHERE `permission` = 'stunden.bearbeiten' AND `role` IN (SELECT `role` FROM `role_permissions` WHERE `permission` = 'stunden.alle.bearbeiten' AND `allowed` = 1);--> statement-breakpoint
-- Die alten Namen werden nicht mehr gebraucht
DELETE FROM `role_permissions` WHERE `permission` IN ('lager.stock.book', 'lager.stock.inventory', 'lager.movements.view', 'lager.movements.correct', 'lager.products.manage', 'lager.reports.view', 'lager.alerts.view', 'stunden.erfassen', 'tagesberichte.erfassen', 'kunden.pflegen', 'verwaltung.masterdata.manage', 'verwaltung.users.manage', 'verwaltung.permissions.manage', 'verwaltung.settings.manage');
